/// Hive Types
const int HIVE_TYPE_ID_USER_VO = 1;
const int HIVE_TYPE_ID_CITIES_VO = 2;
const int HIVE_TYPE_ID_SIGN_IN_WITH_PHONE_RESPONSE = 3;
const int HIVE_TYPE_ID_USER_INFO_VO = 4;
const int HIVE_TYPE_ID_COLOR_VO = 5;

/// Box Names
const String BOX_NAME_USER_VO = "BOX_NAME_USER_VO";
const String BOX_NAME_CITIES_VO = "Box_NAME_CITIES_VO";
const String BOX_NAME_SIGN_WITH_PHONE_RESPONSE = "BOX_NAME_SIGN_IN_WITH_PHONE_RESPONSE";
const String BOX_NAME_USER_INFO_VO = "BOX_NAME_USER_INFO_VO";
const String BOX_NAME_COLOR_VO = "BOX_NAME_COLOR_VO";